[2024-09-02 12:11:35 +0000] [93848] [INFO] Starting gunicorn 23.0.0
[2024-09-02 12:11:35 +0000] [93848] [INFO] Listening at: http://10.178.0.2:8080 (93848)
[2024-09-02 12:11:35 +0000] [93848] [INFO] Using worker: sync
[2024-09-02 12:11:35 +0000] [93849] [INFO] Booting worker with pid: 93849
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/utils/deprecation.py", line 128, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.64.196.23'. You may need to add '34.64.196.23' to ALLOWED_HOSTS.
Bad Request: /login
[2024-09-02 12:19:36 +0000] [93848] [INFO] Handling signal: term
[2024-09-02 21:19:36 +0900] [93849] [INFO] Worker exiting (pid: 93849)
[2024-09-02 12:19:36 +0000] [93848] [INFO] Shutting down: Master
[2024-09-02 12:22:39 +0000] [93928] [INFO] Starting gunicorn 23.0.0
[2024-09-02 12:22:39 +0000] [93928] [INFO] Listening at: http://10.178.0.2:8080 (93928)
[2024-09-02 12:22:39 +0000] [93928] [INFO] Using worker: sync
[2024-09-02 12:22:39 +0000] [93929] [INFO] Booting worker with pid: 93929
Not Found: /api/api/preregister
Not Found: /api/preregister
[2024-09-02 13:26:15 +0000] [93928] [ERROR] Worker (pid:93929) was sent SIGHUP!
[2024-09-02 13:26:15 +0000] [101024] [INFO] Booting worker with pid: 101024
[2024-09-02 13:26:15 +0000] [93928] [INFO] Handling signal: hup
[2024-09-02 13:26:15 +0000] [93928] [INFO] Hang up: Master
[2024-09-02 13:26:15 +0000] [93928] [INFO] Handling signal: term
[2024-09-02 13:26:15 +0000] [101027] [INFO] Booting worker with pid: 101027
[2024-09-02 22:26:15 +0900] [101024] [INFO] Worker exiting (pid: 101024)
[2024-09-02 13:26:45 +0000] [93928] [INFO] Shutting down: Master
[2024-09-02 13:27:50 +0000] [878] [INFO] Starting gunicorn 23.0.0
[2024-09-02 13:27:50 +0000] [878] [INFO] Listening at: http://10.178.0.2:8080 (878)
[2024-09-02 13:27:50 +0000] [878] [INFO] Using worker: sync
[2024-09-02 13:27:50 +0000] [879] [INFO] Booting worker with pid: 879
